PS1='\u@\h:\w\$ '
HISTSIZE=5000
HISTFILESIZE=10000
HISTCONTROL=ignoredups:erasedups
shopt -s histappend
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
export LESS=-R
export EDITOR=vim
export VISUAL=vim
export TERM=xterm-256color
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias gs='git status -sb'
alias gl='git log --oneline --graph --decorate'
alias gc='git commit'
alias gp='git push'
alias gd='git diff'
[ -d "$HOME/.local/bin" ] && export PATH="$HOME/.local/bin:$PATH"
