set number
set relativenumber
syntax on
colorscheme blue
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab
set autoindent
set smartindent
set incsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set scrolloff=4
set sidescrolloff=8
set showmatch
